---
name: CI for ansible-role-abclinuxu_weekly

on: [push]

defaults:
  run:
    working-directory: 'zstyblik.abclinuxu_weekly'

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v4
      with:
        path: 'zstyblik.abclinuxu_weekly'
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt
    - name: Run yamllint
      run: |
        ./ci/run-yamllint.sh
    - name: Run ansible-lint
      uses: ansible/ansible-lint@v24.9.0
      with:
        working_directory: 'zstyblik.abclinuxu_weekly'
